// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import SensorChart from "./sensor_chart_controller"
application.register("sensor-chart", SensorChart)

import ClickableElement from "./clickable_element_controller.js"
application.register("clickable-element", ClickableElement)

import DomManipulations from "./dom_manipulations_controller.js"
application.register("dom-manipulations", DomManipulations)

import Toastify from "./toastify_controller.js"
application.register("toastify", Toastify)

import FormTemplate from "./form_template_controller.js"
application.register("form-template", FormTemplate)

import NavBar from "./nav_bar_controller.js"
application.register("nav-bar", NavBar)
